// Hier alles importeren
import { FlowRouter } from 'meteor/kadira:flow-router';
import { BlazeLayout } from 'meteor/kadira:blaze-layout';
import '../imports/template/full.css'
import '../imports/lib/router.js'
import '../imports/lib/helpers.js'
import '../imports/lib/methods.js'
import '../imports/template/header.html'
import '../imports/template/layout.html'
import '../imports/template/layout.js'
import '../imports/start/start.html'
import '../imports/start/start.js'
import '../imports/story/stories.html'
import '../imports/story/stories.js'
import '../imports/story/story.html'
import '../imports/story/story.js'
import '../imports/admin/admin.html'
import '../imports/admin/admin.js'
import '../imports/admin/settings/settings.html'
import '../imports/admin/settings/settings.js'
import '../imports/admin/stats/stats.html'
import '../imports/admin/stats/stats.js'
import '../imports/admin/stories/filters/filters.html'
import '../imports/admin/stories/filters/filters.js'
import '../imports/admin/stories/story/story.html'
import '../imports/admin/stories/story/story.js'
import '../imports/admin/stories/stories.html'
import '../imports/admin/stories/stories.js'
import '../imports/admin/stories/storySettings/storySettings.html'
import '../imports/admin/stories/storySettings/storySettings.js'
import '../imports/login/login.html'
import '../imports/login/login.js'

import '../imports/user/user.html'
import '../imports/user/user.js'
